// Deklarering av typer av ACTIONS
export const SET_LOCATION = "SET_LOCATION";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const GET_USER_TRIPS = "GET_USER_TRIPS";
export const GET_TRIPS_ERROR = "GET_TRIPS_ERROR";
export const CREATE_TRIP = "CREATE_TRIP";
export const CREATE_TRIP_ERROR = "CREATE_TRIP_ERROR";
export const ADD_RESTAURANT = "ADD_RESTAURANT";

export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
export const FETCH_LOCATION = "FETCH_LOCATION";
