// ACTION types declarations
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const SET_LOCATION = "SET_LOCATION";
export const FETCH_LOCATION = "FETCH_LOCATION";
export const LOCATION_ERROR = "LOCATION_ERROR";
export const RESET_LOCATION = "RESET_LOCATION";
export const EDIT_LOCATION = 'EDIT_LOCATION';

export const GET_USER_TRIPS = "GET_USER_TRIPS";
export const GET_TRIPS_ERROR = "GET_TRIPS_ERROR";
export const CREATE_TRIP = "CREATE_TRIP";
export const CREATE_TRIP_ERROR = "CREATE_TRIP_ERROR";
export const ADD_TRIP = "ADD_TRIP";
export const RESET_TRIP = "RESET_TRIP";
export const REMOVE_TRIP = 'REMOVE_TRIP';
export const REMOVE_TRIP_ERROR = 'REMOVE_TRIP_ERROR';

export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
export const FETCH_RESTAURANTS_ERROR = "FETCH_RESTAURANTS_ERROR";
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const RESET_RESTAURANTS = "RESET_RESTAURANTS";
export const ADD_RESTAURANTS = 'ADD_RESTAURANTS';
export const REMOVE_RESTAURANT = 'REMOVE_RESTAURANT';

export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const ADD_ACTIVITIES = 'ADD_ACTIVITIES';
export const FETCH_ACTIVITIES_ERROR = "FETCH_ACTIVITIES_ERROR";
export const RESET_ACTIVITIES = "RESET_ACTIVITIES";
export const REMOVE_ACTIVITY = 'REMOVE_ACTIVITY';

export const FETCH_ACCOMMODATIONS = "FETCH_ACCOMMODATIONS";
export const FETCH_ACCOMMODATIONS_ERROR = "FETCH_ACCOMMODATIONS_ERROR";
export const RESET_ACCOMMODATIONS = "RESET_ACCOMMODATIONS";
export const ADD_ACCOMMODATION = "ADD_ACCOMMODATION";
export const ADD_ACCOMMODATIONS = 'ADD_ACCOMMODATIONS';
export const REMOVE_ACCOMMODATION = 'REMOVE_ACCOMMODATION';